import test from "node:test";
import assert from "node:assert/strict";
import { enrichCalendarEvent } from "../lib/calendar/enrich-events";
import { ERRAND_TRANSITION_BUFFER_MINUTES, errandSlotKey, scheduleErrands } from "../lib/errands/schedule-errands";
import type { CalendarEvent, Errand } from "../lib/types";

const date="2026-08-18",timezone="America/New_York";
const event=(id:string,start:string,end:string,overrides:Partial<CalendarEvent>={})=>enrichCalendarEvent({id,title:id,startAt:`${date}T${start}:00-04:00`,endAt:`${date}T${end}:00-04:00`,allDay:false,status:"confirmed",...overrides});
const errand=(id:string,estimatedMinutes=20,overrides:Partial<Errand>={}):Errand=>({id,title:id,estimatedMinutes,priority:"normal",status:"open",...overrides});
const time=(value?:string)=>value?.slice(11,16);

test("fits an errand in a protected calendar gap",()=>{const [slot]=scheduleErrands([errand("mail",20,{earliestStart:"11:00"})],[event("work","09:00","11:00"),event("lunch","12:00","13:00")],date,timezone);assert.equal(slot.status,"scheduled");assert.equal(time(slot.startAt),"15:10");assert.equal(time(slot.endAt),"15:30");assert.equal(slot.afterEventId,"work");assert.equal(slot.beforeEventId,"lunch")});
test("too-long errands return an explicit no-fit state",()=>{const [slot]=scheduleErrands([errand("long",900)],[event("middle","12:00","18:00")],date,timezone);assert.equal(slot.status,"no-fit");assert.match(slot.reason,/couldn't find/i)});
test("deadline and earliest-start constraints are respected",()=>{const slots=scheduleErrands([errand("deadline",30,{completeBy:"11:00"}),errand("later",20,{earliestStart:"14:30"})],[],date,timezone);assert.ok(new Date(slots[0].endAt!).getTime()<=new Date("2026-08-18T15:00:00Z").getTime());assert.ok(new Date(slots[1].startAt!).getTime()>=new Date("2026-08-18T18:30:00Z").getTime())});
test("calendar events and the transition cushion are never overlapped",()=>{const events=[event("work","09:00","11:00"),event("lunch","12:00","13:00")],[slot]=scheduleErrands([errand("mail",40,{earliestStart:"11:00"})],events,date,timezone);assert.equal(ERRAND_TRANSITION_BUFFER_MINUTES,10);assert.equal(time(slot.startAt),"15:10");assert.equal(time(slot.endAt),"15:50")});
test("two errands fit sequentially without overlap",()=>{const slots=scheduleErrands([errand("a",20),errand("b",30)],[event("work","08:00","11:00"),event("lunch","12:10","14:00")],date,timezone);assert.equal(slots.every(slot=>slot.status==="scheduled"),true);const ordered=slots.toSorted((a,b)=>a.startAt!.localeCompare(b.startAt!));assert.ok(new Date(ordered[0].endAt!).getTime()<=new Date(ordered[1].startAt!).getTime())});
test("completed errands are ignored",()=>{assert.deepEqual(scheduleErrands([errand("done",20,{status:"completed"})],[],date,timezone),[])});
test("deadline and high-priority errands place before normal and low priority",()=>{const slots=scheduleErrands([errand("low",30,{priority:"low"}),errand("high",30,{priority:"high"}),errand("deadline",30,{completeBy:"18:00"}),errand("normal",30)],[],date,timezone);assert.deepEqual(slots.map(slot=>slot.errandId),["deadline","high","normal","low"])});
test("calendar cancellation creates a slot and restoration removes it",()=>{const busy=[event("morning","08:00","12:00"),event("opening","12:00","14:00"),event("evening","14:00","22:00")],cancelled=busy.map(item=>item.id==="opening"?{...item,status:"cancelled" as const}:item);assert.equal(scheduleErrands([errand("arbitrary-errand-id",60)],busy,date,timezone)[0].status,"no-fit");assert.equal(scheduleErrands([errand("arbitrary-errand-id",60)],cancelled,date,timezone)[0].status,"scheduled");assert.equal(scheduleErrands([errand("arbitrary-errand-id",60)],busy,date,timezone)[0].status,"no-fit")});
test("all-day events do not erase flexible daytime windows",()=>{const allDay=event("all-day","00:00","23:59",{allDay:true,startAt:date,endAt:"2026-08-19"});assert.equal(scheduleErrands([errand("mail")],[allDay],date,timezone)[0].status,"scheduled")});
test("a rejected slot is not immediately proposed again",()=>{const errands=[errand("mail")],first=scheduleErrands(errands,[],date,timezone)[0],second=scheduleErrands(errands,[],date,timezone,{mail:[errandSlotKey(first)]})[0];assert.equal(second.status,"scheduled");assert.notEqual(second.startAt,first.startAt)});
test("scheduling is deterministic for arbitrary IDs",()=>{const errands=[errand("anything-9",20),errand("anything-2",25,{priority:"high"})],events=[event("fixed-A","10:00","11:00")];assert.deepEqual(scheduleErrands(errands,events,date,timezone),scheduleErrands(errands,events,date,timezone))});
test("today never proposes a slot in the past",()=>{const [slot]=scheduleErrands([errand("mail")],[],date,timezone,{},new Date("2026-08-18T16:35:00Z"));assert.equal(time(slot.startAt),"16:35")});
test("an impossible 180-minute deadline errand remains open with a no-fit result",()=>{const value=errand("cake",180,{completeBy:"10:00"}),[result]=scheduleErrands([value],[],date,timezone,{},new Date("2026-08-18T13:00:00Z"));assert.equal(value.status,"open");assert.equal(result.status,"no-fit");assert.match(result.reason,/before 10:00 AM/i)});
test("rejection reschedules when another slot exists and clearing it restores eligibility",()=>{const values=[errand("mail",20)],first=scheduleErrands(values,[],date,timezone)[0],rejections={mail:[errandSlotKey(first)]},second=scheduleErrands(values,[],date,timezone,rejections)[0],restored=scheduleErrands(values,[],date,timezone,{mail:[]})[0];assert.equal(second.status,"scheduled");assert.notEqual(second.startAt,first.startAt);assert.equal(restored.startAt,first.startAt)});
test("rejection returns no-fit without closing the errand when the only slot is exhausted",()=>{const values=[errand("cake",20,{earliestStart:"11:00",completeBy:"11:30"})],events=[event("before","08:00","11:00"),event("after","11:40","22:00")],first=scheduleErrands(values,events,date,timezone)[0],second=scheduleErrands(values,events,date,timezone,{cake:[errandSlotKey(first)]})[0];assert.equal(first.status,"scheduled");assert.equal(second.status,"no-fit");assert.equal(values[0].status,"open")});
test("calendar cancellation exposes a better earlier slot and restoration moves the errand back",()=>{const values=[errand("mail",20,{earliestStart:"16:00"})],blocker=event("arbitrary-blocker","15:50","17:50"),withBlock=scheduleErrands(values,[blocker],date,timezone)[0],withoutBlock=scheduleErrands(values,[],date,timezone)[0],restored=scheduleErrands(values,[blocker],date,timezone)[0];assert.ok(new Date(withoutBlock.startAt!).getTime()<new Date(withBlock.startAt!).getTime());assert.equal(restored.startAt,withBlock.startAt)});
test("calendar cancellation leaves an already optimal slot unchanged when it opens nothing better",()=>{const values=[errand("mail",20,{earliestStart:"16:00"})],later=event("later","20:00","21:00"),withEvent=scheduleErrands(values,[later],date,timezone)[0],withoutEvent=scheduleErrands(values,[],date,timezone)[0];assert.equal(withEvent.startAt,withoutEvent.startAt)});
