import test from "node:test";
import assert from "node:assert/strict";
import { buildReadyChanges, type ReadyChangeTrigger, type ReadyDaySnapshot } from "../lib/changes/build-ready-changes";

const trigger:ReadyChangeTrigger={type:"calendar-event-cancelled",id:"event-anything",title:"Pilates"};
const snapshot=(overrides:Partial<ReadyDaySnapshot>={}):ReadyDaySnapshot=>({eventIds:[],events:[],recommendations:[],errands:[],outfitTransitions:[],peoplePrepEvents:[],...overrides});

test("detects arbitrary event removal and restoration",()=>{const withEvent=snapshot({eventIds:["random-42"],events:[{id:"random-42",title:"Studio"}]});assert.equal(buildReadyChanges(withEvent,snapshot(),trigger)[0].type,"event-removed");assert.equal(buildReadyChanges(snapshot(),withEvent,{...trigger,type:"calendar-event-restored"})[0].type,"event-added")});
test("detects an errand move but identical timestamps produce no fake movement",()=>{const before=snapshot({errands:[{id:"mail",title:"Mail package",status:"scheduled",startAt:"2026-08-19T20:40:00Z"}]}),moved=snapshot({errands:[{id:"mail",title:"Mail package",status:"scheduled",startAt:"2026-08-19T17:20:00Z"}]});assert.equal(buildReadyChanges(before,moved,trigger)[0].type,"errand-moved");assert.deepEqual(buildReadyChanges(before,before,trigger),[])});
test("detects recommendation removal and addition",()=>{const recommendation={id:"gym",title:"Pack gym clothes",priority:"essential" as const},withRec=snapshot({recommendations:[recommendation]});assert.equal(buildReadyChanges(withRec,snapshot(),trigger)[0].type,"recommendation-removed");assert.equal(buildReadyChanges(snapshot(),withRec,trigger)[0].type,"recommendation-added")});
test("detects transition removal",()=>{assert.equal(buildReadyChanges(snapshot({outfitTransitions:["Workout transition"]}),snapshot(),trigger)[0].type,"transition-removed")});
test("detects People Prep availability",()=>{const withPrep=snapshot({peoplePrepEvents:[{eventId:"lunch-any-id",eventTitle:"Lunch with Jessica"}]});assert.equal(buildReadyChanges(snapshot(),withPrep,trigger)[0].type,"people-prep-added")});
test("detects no-fit errands becoming schedulable and the reverse",()=>{const noFit=snapshot({errands:[{id:"cake",title:"Pick up cake",status:"no-fit"}]}),fits=snapshot({errands:[{id:"cake",title:"Pick up cake",status:"scheduled",startAt:"2026-08-19T16:40:00Z"}]});assert.equal(buildReadyChanges(noFit,fits,trigger)[0].type,"errand-now-fits");assert.equal(buildReadyChanges(fits,noFit,trigger)[0].type,"errand-no-longer-fits")});
test("unchanged fields are omitted",()=>{const value=snapshot({eventIds:["a"],events:[{id:"a",title:"Anything"}],recommendations:[{id:"r",title:"Bring notes",priority:"helpful"}],outfitTransitions:["Layer"]});assert.deepEqual(buildReadyChanges(value,value,trigger),[])});
test("maximum count and impact ranking are respected",()=>{const before=snapshot({events:[{id:"event-anything",title:"Pilates"}],eventIds:["event-anything"],errands:[{id:"risk",title:"Birthday cake",status:"scheduled",startAt:"2026-08-19T16:00:00Z"},{id:"move",title:"Mail",status:"scheduled",startAt:"2026-08-19T18:00:00Z"}],recommendations:[{id:"gym",title:"Pack gym clothes",priority:"essential"}],peoplePrepEvents:[{eventId:"social",eventTitle:"Dinner"}]}),after=snapshot({errands:[{id:"risk",title:"Birthday cake",status:"no-fit"},{id:"move",title:"Mail",status:"scheduled",startAt:"2026-08-19T19:00:00Z"}]});const changes=buildReadyChanges(before,after,trigger,3);assert.equal(changes.length,3);assert.deepEqual(changes.map(item=>item.type),["errand-no-longer-fits","event-removed","errand-moved"])});
