import test from "node:test";
import assert from "node:assert/strict";
import { enrichCalendarEvent } from "../lib/calendar/enrich-events";
import { buildPeoplePrepForDay, buildSocialPrep, MAX_SOCIAL_PREP_BULLETS, socialDismissalKey } from "../lib/social/build-social-prep";
import { curatedInterestEnrichments } from "../lib/social/interest-enrichment";
import { matchPeopleToEvent } from "../lib/social/match-people";
import type { CalendarEvent, InterestEnrichment, Person, SocialContextItem } from "../lib/types";

const person=(overrides:Partial<Person>={}):Person=>({id:"person-j",name:"Jessica",relationship:"friend",interests:[],bondTopics:[],...overrides});
const event=(title="Lunch with Jessica",id="arbitrary-calendar-id")=>enrichCalendarEvent({id,title,startAt:"2026-08-20T12:30:00-04:00",endAt:"2026-08-20T13:30:00-04:00",allDay:false,status:"confirmed"} satisfies CalendarEvent);
const note=(id:string,content:string,overrides:Partial<SocialContextItem>={}):SocialContextItem=>({id,personId:"person-j",type:"conversation",content,importance:"normal",...overrides});

test("event matching is person-driven, case insensitive, and independent of calendar IDs",()=>{const j=person();assert.deepEqual(matchPeopleToEvent(event("LUNCH WITH JESSICA","anything-77"),[j]).map(value=>value.id),[j.id]);assert.deepEqual(matchPeopleToEvent(event("Portfolio review with Jessica","other-id"),[j]).map(value=>value.id),[j.id])});
test("unknown and extremely short people do not create false matches",()=>{assert.deepEqual(matchPeopleToEvent(event("Lunch with Jordan"),[person()]),[]);assert.deepEqual(matchPeopleToEvent(event("Dinner with Al"),[person({id:"al",name:"Al"})]),[])});
test("one day derivation is the source consumed by Today and Journey",()=>{const j=person({bondTopics:["restaurants"]}),results=buildPeoplePrepForDay([event()],[j],[]);assert.equal(results.length,1);const todayResult=results[0],journeyResult=results.find(result=>result.event.id===event().id);assert.strictEqual(todayResult,journeyResult);assert.equal(todayResult.person.id,j.id)});
test("recent context produces grounded source metadata",()=>{const item=note("job","Jessica started a new job and said she was nervous about her first week.",{importance:"important"}),result=buildSocialPrep(person(),[item],event())!;assert.equal(result.bullets[0].sources[0].ref,"job");assert.equal(result.bullets[0].sources[0].kind,"social-context");assert.match(result.bullets[0].text,/new job/i)});
test("turtle enrichment combines person interest and provider fact with both sources",()=>{const result=buildSocialPrep(person({interests:["turtles"]}),[],event(),{},curatedInterestEnrichments)!;assert.match(result.bullets[0].text,/Jessica loves turtles.*magnetic field/i);assert.deepEqual(result.bullets[0].sources.map(source=>source.kind),["person-interest","interest-enrichment"]);assert.doesNotMatch(result.bullets[0].text,/aquarium|owns a turtle|Galápagos/i)});
test("sparse interest context never pretends the pair discussed the topic",()=>{const result=buildSocialPrep(person({interests:["turtles"]}),[],event(),{},curatedInterestEnrichments)!;assert.doesNotMatch(result.bullets[0].text,/we talked|you both|last time/i)});
test("unsupported interests remain useful without an invented fact",()=>{const result=buildSocialPrep(person({interests:["ceramics"]}),[],event(),{},curatedInterestEnrichments)!;assert.equal(result.bullets[0].text,"Jessica is interested in ceramics.");assert.deepEqual(result.bullets[0].sources.map(source=>source.kind),["person-interest"])});
test("shared context is distinct from person interests and avoids duplicate topics",()=>{const result=buildSocialPrep(person({interests:["reality TV","turtles"],bondTopics:["Reality TV"]}),[],event(),{},curatedInterestEnrichments)!;assert.equal(result.bullets.filter(bullet=>/reality tv/i.test(bullet.text)).length,1);assert.equal(result.bullets[0].category,"shared_interest")});
test("important personal context outranks enrichment and fills the four-bullet cap",()=>{const context=[note("job","Jessica started a new job and was nervous.",{importance:"important"}),note("family","Jessica shared a recent family update.",{importance:"important"}),note("trip","Jessica is planning a birthday trip.",{importance:"important"}),note("review","I told Jessica I had a portfolio review.",{importance:"important"})],result=buildSocialPrep(person({interests:["turtles"]}),context,event(),{},curatedInterestEnrichments)!;assert.equal(result.bullets.length,MAX_SOCIAL_PREP_BULLETS);assert.ok(result.bullets.every(bullet=>bullet.category!=="conversation_spark"))});
test("user-told context produces a grounded they-may-ask reminder",()=>{const result=buildSocialPrep(person(),[note("portfolio","I told Jessica I had an important portfolio review coming up.")],event())!;assert.equal(result.bullets[0].category,"they_may_ask");assert.match(result.bullets[0].text,/told Jessica.*portfolio review.*may ask/i)});
test("event-scoped dismissal hides a spark without changing the profile",()=>{const j=person({interests:["turtles"]}),initial=buildSocialPrep(j,[],event(),{},curatedInterestEnrichments)!,hidden=initial.bullets[0],dismissals={[socialDismissalKey(event().id,hidden.id)]:true};assert.equal(buildSocialPrep(j,[],event(),dismissals,curatedInterestEnrichments),undefined);assert.deepEqual(j.interests,["turtles"]);assert.ok(buildSocialPrep(j,[],event("Coffee with Jessica","future-event"),dismissals,curatedInterestEnrichments))});
test("day derivation excludes cancelled and already-ended events when a clock is supplied",()=>{const j=person({bondTopics:["design"]}),upcoming=event(),past={...event("Breakfast with Jessica","past"),startAt:"2026-08-20T08:00:00-04:00",endAt:"2026-08-20T09:00:00-04:00"};assert.deepEqual(buildPeoplePrepForDay([past,upcoming],[j],[],{},[],new Date("2026-08-20T10:00:00-04:00").getTime()).map(result=>result.event.id),[upcoming.id])});
test("real recent updates require provider metadata",()=>{const recent:InterestEnrichment={id:"news",topic:"turtles",kind:"recent-update",text:"A sourced update.",sourceLabel:"Example source",sourceUrl:"https://example.com/story",publishedAt:"2026-08-20"};const result=buildSocialPrep(person({interests:["turtles"]}),[],event(),{},[recent])!;assert.equal(result.bullets[0].sources.at(-1)?.label,"Example source")});
