import type { TravelContext, TravelMode, TravelProvider } from "../types";
import { TravelProviderError } from "./travel";

const ROUTES_URL="https://routes.googleapis.com/directions/v2:computeRoutes";
export const GOOGLE_ROUTE_MODE:Record<TravelMode,string>={walking:"WALK",driving:"DRIVE",transit:"TRANSIT",cycling:"BICYCLE"};
function durationMinutes(value:unknown){if(typeof value!=="string"||!/^\d+(?:\.\d+)?s$/.test(value))return null;return Math.max(1,Math.ceil(Number(value.slice(0,-1))/60))}
function distanceLabel(value:unknown){if(typeof value!=="number"||value<0)return undefined;const miles=value/1609.344;return miles<.1?`${Math.round(value)} m`:`${miles.toFixed(miles<10?1:0)} mi`}

type GoogleErrorPayload={error?:{code?:unknown;status?:unknown;message?:unknown;details?:Array<{reason?:unknown}>}};
function safeProviderMessage(value:unknown,apiKey:string){if(typeof value!=="string")return undefined;return value.replaceAll(apiKey,"[REDACTED]").replace(/AIza[A-Za-z0-9_-]{20,}/g,"[REDACTED]").slice(0,300)}
function googleErrorDetails(payload:GoogleErrorPayload,status:number,apiKey:string){const error=payload.error,googleCode=typeof error?.code==="number"?error.code:undefined,googleStatus=typeof error?.status==="string"?error.status:undefined,reason=error?.details?.find(detail=>typeof detail.reason==="string")?.reason,providerMessage=safeProviderMessage(error?.message,apiKey);return {provider:"google_routes" as const,upstreamStatus:status,...(googleCode!==undefined?{googleCode}:{}),...(googleStatus?{googleStatus}:{}),...(typeof reason==="string"?{reason}:{}),...(providerMessage?{providerMessage}:{})}}
function safeGoogleMessage(status:number,reason?:string){if(status===400)return "Google Routes rejected the route request.";if(status===403)return reason==="API_KEY_SERVICE_BLOCKED"?"Routes API rejected the API key restrictions.":reason==="SERVICE_DISABLED"?"Routes API is disabled for this Google Cloud project.":"Routes API rejected the API key or project configuration.";if(status===429)return "Google Routes quota was exceeded.";if(status>=500)return "Google Routes is temporarily unavailable.";return "Travel time unavailable"}

export function createGoogleRoutesProvider(options:{apiKey:string;fetcher?:typeof fetch}):TravelProvider{const fetcher=options.fetcher??globalThis.fetch;return {async getTravelTime(request){const response=await fetcher(ROUTES_URL,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":options.apiKey,"x-goog-fieldmask":"routes.duration,routes.distanceMeters"},body:JSON.stringify({origin:{address:request.origin},destination:{address:request.destination},travelMode:GOOGLE_ROUTE_MODE[request.mode],...(request.arrivalAt&&request.mode==="transit"?{arrivalTime:request.arrivalAt}:{})})});if(!response.ok){let payload:GoogleErrorPayload={};try{payload=await response.json() as GoogleErrorPayload}catch{/* retain status-only diagnostics */}const details=googleErrorDetails(payload,response.status,options.apiKey);throw new TravelProviderError(safeGoogleMessage(response.status,details.reason),response.status,details)}let payload:{routes?:Array<{duration?:unknown;distanceMeters?:unknown}>};try{payload=await response.json() as typeof payload}catch{throw new TravelProviderError("Travel provider returned an invalid response",502,{provider:"google_routes",upstreamStatus:response.status,reason:"MALFORMED_RESPONSE"})};const route=payload.routes?.[0],minutes=durationMinutes(route?.duration);if(!route||minutes===null)throw new TravelProviderError("No route was found for these locations",422,{provider:"google_routes",upstreamStatus:response.status,reason:"NO_ROUTE"});return {origin:request.origin,destination:request.destination,mode:request.mode,durationMinutes:minutes,...(distanceLabel(route.distanceMeters)?{distance:distanceLabel(route.distanceMeters)}:{})} as TravelContext}}}
