import { demoWeatherLocation } from "./ready-config";
import { enrichCalendarEvents } from "./calendar/enrich-events";
import type { CalendarEvent, ClosetItem, SleepContext, TodoistTask, WeatherContext } from "./types";
function demoDateTime(date:string,time:string):string{const zoneName=new Intl.DateTimeFormat("en-US",{timeZone:demoWeatherLocation.timezone,timeZoneName:"longOffset"}).formatToParts(new Date(`${date}T12:00:00Z`)).find(part=>part.type==="timeZoneName")?.value;const offset=zoneName?.replace("GMT","")||"Z";return `${date}T${time}:00${offset}`}
export function demoCalendarEvents(date:string):CalendarEvent[]{return [
  {id:"studio",title:"Design Studio",startAt:demoDateTime(date,"09:00"),endAt:demoDateTime(date,"12:00"),allDay:false,location:"West Hall",status:"confirmed"},
  {id:"lunch-jessica",title:"Lunch with Jessica",startAt:demoDateTime(date,"12:30"),endAt:demoDateTime(date,"13:30"),allDay:false,location:"Little Sister",status:"confirmed"},
  {id:"review",title:"Portfolio Review",startAt:demoDateTime(date,"15:00"),endAt:demoDateTime(date,"16:00"),allDay:false,location:"Design Center",status:"confirmed"},
  {id:"pilates",title:"Pilates",startAt:demoDateTime(date,"17:30"),endAt:demoDateTime(date,"18:30"),allDay:false,location:"Form Studio",status:"confirmed"},
  {id:"evening",title:"Walk the Dog",startAt:demoDateTime(date,"19:30"),endAt:demoDateTime(date,"20:15"),allDay:false,location:"Neighborhood Loop",status:"confirmed"},
  {id:"home",title:"Wind Down",startAt:demoDateTime(date,"21:30"),endAt:demoDateTime(date,"22:30"),allDay:false,location:"Home",status:"confirmed"},
]}
export const events=enrichCalendarEvents(demoCalendarEvents("2026-08-16"));
export const tasks:TodoistTask[]=[{id:"prototype",title:"Bring physical prototype",dueToday:true,physicalItem:"prototype"},{id:"library",title:"Return library book",dueToday:true,physicalItem:"library book"},{id:"detergent",title:"Buy detergent",dueToday:true}];
export const weather:WeatherContext={currentTemp:57,morningTemp:57,eveningTemp:48,highTemp:66,lowTemp:47,uvIndex:7,currentCondition:"Bright start",conditionCode:"clear",precipitationStart:"5:00 PM",location:demoWeatherLocation}; export const sleep:SleepContext={durationMinutes:358,baselineMinutes:440};
const item=(id:string,name:string,category:ClosetItem["category"],color:string,formality:number,warmth:number,weatherResistance:number,walkingComfort:number,activityTypes:string[]):ClosetItem=>({id,name,category,image:"",color,formality,warmth,weatherResistance,walkingComfort,activityTypes,clean:true,lastWorn:"2026-08-10"});
export const closet:ClosetItem[]=[item("white-top","Ivory ribbed top","Tops","Ivory",3,2,1,4,["everyday","professional","dinner"]),item("blue-shirt","Sky poplin shirt","Tops","Sky",4,2,1,4,["professional","presentation","dinner"]),item("trousers","Black wide-leg trousers","Bottoms","Black",4,3,2,4,["professional","presentation","dinner"]),item("jeans","Indigo straight jeans","Bottoms","Indigo",2,3,2,4,["casual","everyday","walking"]),item("blazer","Lavender blazer","Outerwear","Lavender",5,3,1,3,["professional","presentation","dinner"]),item("raincoat","Plum rain shell","Outerwear","Plum",2,4,5,4,["rain","walking","layering"]),item("sneakers","Cream walking sneakers","Shoes","Cream",2,2,2,5,["walking","casual","everyday"]),item("loafers","Black soft loafers","Shoes","Black",4,2,2,4,["professional","presentation","dinner"]),item("workout-top","Berry workout top","Workout","Berry",1,1,2,5,["exercise","walking"]),item("leggings","Black leggings","Workout","Black",1,2,2,5,["exercise","casual"]),item("tote","Indigo carryall","Bags","Indigo",3,1,2,4,["work","everyday","gym"]),item("scarf","Sunrise silk scarf","Accessories","Yellow",4,2,1,4,["dinner","presentation","layering"])];
