import { inspectGoogleMapsApiKey } from "@/lib/travel/google-api-key";
import { createGoogleRoutesProvider } from "@/lib/travel/google-routes";
import { TravelProviderError } from "@/lib/travel/travel";
import type { TravelMode, TravelRequest } from "@/lib/types";

const MODES=new Set<TravelMode>(["walking","driving","transit","cycling"]);
function developmentDetails(error:TravelProviderError){return process.env.NODE_ENV==="production"?{}:{status:"travel_error",provider:"google_routes",upstreamStatus:error.details.upstreamStatus,reason:error.details.reason??error.details.googleStatus??"UNKNOWN",googleCode:error.details.googleCode,googleStatus:error.details.googleStatus,message:error.details.providerMessage??error.message}}

export async function POST(request:Request){
  let input:Partial<TravelRequest>;try{input=await request.json() as Partial<TravelRequest>}catch{return Response.json({error:"Invalid travel request"},{status:400})}
  if(typeof input.origin!=="string"||!input.origin.trim()||input.origin.length>300||typeof input.destination!=="string"||!input.destination.trim()||input.destination.length>300||!input.mode||!MODES.has(input.mode))return Response.json({error:"A valid origin, destination, and travel mode are required"},{status:400});
  const key=inspectGoogleMapsApiKey(process.env.GOOGLE_MAPS_API_KEY),apiKey=key.normalizedKey;
  if(!apiKey){const reason=key.formatIssue??"INVALID_API_KEY_FORMAT",message=reason==="MISSING_API_KEY"?"GOOGLE_MAPS_API_KEY is not configured.":"GOOGLE_MAPS_API_KEY does not appear to contain a valid Google API key.";if(process.env.NODE_ENV!=="production")console.error("Google Routes request not sent",{reason,apiKeyDetected:key.apiKeyDetected,apiKeyLooksValid:key.apiKeyLooksValid,apiKeyLength:key.apiKeyLength,apiKeyPrefix:key.apiKeyPrefix,mode:input.mode,originSupplied:true,destinationSupplied:true});return Response.json({error:message,...(process.env.NODE_ENV!=="production"?{status:"travel_error",provider:"google_routes",reason,apiKeyDetected:key.apiKeyDetected,apiKeyLooksValid:key.apiKeyLooksValid,apiKeyLength:key.apiKeyLength,apiKeyPrefix:key.apiKeyPrefix}:{})},{status:503,headers:{"cache-control":"no-store"}})}
  try{const provider=createGoogleRoutesProvider({apiKey});const travel=await provider.getTravelTime({origin:input.origin.trim(),destination:input.destination.trim(),mode:input.mode,...(typeof input.arrivalAt==="string"?{arrivalAt:input.arrivalAt}:{})});return Response.json(travel,{headers:{"cache-control":"no-store"}})}catch(error){if(!(error instanceof TravelProviderError))return Response.json({error:"Travel time unavailable"},{status:502,headers:{"cache-control":"no-store"}});if(process.env.NODE_ENV!=="production")console.error("Google Routes request failed",{upstreamStatus:error.details.upstreamStatus,googleCode:error.details.googleCode,googleStatus:error.details.googleStatus,reason:error.details.reason??"UNKNOWN",message:error.details.providerMessage??error.message,apiKeyDetected:true,mode:input.mode,originSupplied:true,destinationSupplied:true});return Response.json({error:error.message,...developmentDetails(error)},{status:error.status,headers:{"cache-control":"no-store"}})}
}
