import type { PreparationTask, PreparationTaskState, ReadyEvent } from "../types";
import { prioritizePreparationTasks } from "../preparation/prioritize-tasks";

function task(id:string,title:string,category:PreparationTask["category"],priority:number,reason:string):PreparationTask{return {id,title,category,priority,reason,generated:true}}
export function buildPreparationTasks(event:ReadyEvent):PreparationTask[]{
  const t:PreparationTask[]=[],text=`${event.title} ${event.description??""}`.toLowerCase(),add=(...value:Parameters<typeof task>)=>t.push(task(...value));
  if(event.type==="home")return [];
  switch(event.category){
    case "critique":add("laptop","Pack laptop","bring",1,`${event.title} may depend on your digital work.`);add("sketchbook","Bring sketchbook","bring",1,"A sketchbook supports critique notes and visual feedback.");add("previous-feedback","Review previous feedback","review",1,"Carry earlier feedback into this critique.");add("latest-design-file","Open latest design file","do",1,"Have the latest work accessible before the critique.");add("feedback-questions","Prepare 3 feedback questions","do",1,"Decide what feedback would be most useful.");if(/prototype|model|mockup/.test(text))add("prototype","Bring prototype or mockup","bring",1,"The event details mention a physical prototype or mockup.");break;
    case "presentation":add("review-slides","Review slides","review",1,"The event is classified as a presentation.");add("presentation-file","Confirm presentation file is accessible","do",1,"Avoid a last-minute file handoff problem.");add("charge-laptop","Charge laptop","bring",1,"A charged device may be required to present.");add("talking-points","Practice key talking points","do",1,"Rehearse the most important ideas.");if(/prototype|materials|sample/.test(text))add("presentation-materials","Bring presentation materials","bring",1,"The event details mention materials or a prototype.");break;
    case "coffee_chat":add("review-person","Review who you’re meeting","review",1,event.attendees?.length?`The event includes ${event.attendees.length} attendee${event.attendees.length===1?"":"s"}.`:"The event is a one-to-one conversation.");add("conversation-questions","Prepare 3 questions","do",1,"Choose what you want to learn from the conversation.");add("review-context","Review notes or company context","review",2,"A little context can make the conversation more useful.");break;
    case "interview":add("company-notes","Review role and company notes","review",1,"The event is classified as an interview.");add("work-examples","Prepare examples of past work","do",1,"Specific examples can support interview answers.");add("interview-questions","Prepare interview questions","do",1,"Bring questions you genuinely want answered.");add("portfolio","Bring or open portfolio","bring",1,"Keep relevant work accessible.");add(event.meetingUrl?"meeting-link":"confirm-location",event.meetingUrl?"Open interview link":"Confirm interview location",event.meetingUrl?"do":"timing",1,event.meetingUrl?"A virtual link is available.":"A physical location is available.");break;
    case "class":add("class-notes","Review class notes","review",1,"The event is classified as a class or studio session.");add("class-materials","Check required materials","do",1,"Confirm what this session specifically requires.");add("laptop-notebook","Bring laptop or notebook","bring",2,"Keep your working materials available.");add("assignment-status","Review assignment or project status","review",2,"Know where your current work stands.");break;
    case "virtual_meeting":add("meeting-link","Open meeting link","do",1,"The calendar includes a virtual meeting link.");add("av-check","Check microphone and camera","do",1,"Confirm the virtual setup before joining.");add("review-agenda","Review agenda","review",2,event.description?"The event description may contain the agenda.":"Know what the meeting needs to accomplish.");add("join-early","Join 5 minutes early","timing",2,"Allow a short connection buffer.");break;
    case "meeting":add("review-agenda","Review agenda","review",1,event.description?"The event description may contain meeting context.":"Clarify what the meeting needs to accomplish.");add("talking-points","Prepare talking points","do",1,"Identify the points you need to contribute.");add("relevant-documents","Bring or open relevant documents","bring",2,"Keep supporting material accessible.");if(event.attendees?.length)add("review-attendees","Review attendees","review",2,`${event.attendees.length} attendee${event.attendees.length===1?" is":"s are"} listed.`);break;
    case "workout":add("water-bottle","Bring water bottle","bring",1,"The event is classified as a workout.");add("workout-clothes","Pack workout clothes","bring",1,"Bring clothing suited to the activity.");add("workout-shoes","Bring appropriate shoes","bring",1,"Footwear may be activity-dependent.");add("workout-plan","Check workout plan","review",2,"Know what session you intend to complete.");break;
    case "study":add("top-priority","Identify the top priority","do",1,"Give the focus block a clear outcome.");add("required-files","Open required files","do",1,"Reduce setup time when the block begins.");add("charger","Bring charger","bring",2,"Keep devices available for the full block.");add("reference-materials","Gather reference materials","bring",2,"Have the sources you expect to use nearby.");break;
    case "appointment":add("appointment-details","Review appointment details","review",1,"Confirm what the appointment requires.");if(event.location)add("confirm-location","Confirm location","timing",1,"The calendar includes a physical location.");add("appointment-materials","Bring required documents or materials","bring",2,"Only bring items you already know are required.");break;
    case "travel":add("travel-details","Review booking and timing details","review",1,"The event is classified as travel.");add("travel-documents","Bring required travel documents","bring",1,"Confirm the documents required for this trip.");add("travel-bag","Check essential items","do",2,"Review your essentials before leaving.");break;
    case "social":add("social-details","Review event details","review",2,"Check the available social-event context.");if(event.location)add("confirm-location","Confirm location","timing",2,"The calendar includes a location.");break;
    default:add("review-details","Review event details","review",3,"Ready has limited context for this event.");if(event.meetingUrl)add("meeting-link","Open meeting link","do",2,"A virtual meeting link is available.");else if(event.location)add("confirm-location","Confirm location","timing",3,"The calendar includes a location.");
  }
  if(event.meetingUrl&&event.category!=="virtual_meeting"&&!t.some(value=>value.id==="meeting-link"))add("meeting-link","Open meeting link","do",2,"A virtual meeting link is available.");
  return prioritizePreparationTasks(t,6);
}

export function preparationStateKey(eventId:string,taskId:string){return `${eventId}::${taskId}`}
export function isPreparationTaskComplete(state:PreparationTaskState,eventId:string,taskId:string){return Boolean(state[preparationStateKey(eventId,taskId)])}
export function upcomingEvents(events:ReadyEvent[],now=new Date()):ReadyEvent[]{return events.filter(event=>event.status!=="cancelled"&&(event.allDay?new Date(`${event.endAt}T00:00:00`).getTime()>now.getTime():new Date(event.endAt).getTime()>now.getTime())).sort((a,b)=>a.startAt.localeCompare(b.startAt))}
export function nextUpcomingEvent(events:ReadyEvent[],now=new Date()):ReadyEvent|undefined{const upcoming=upcomingEvents(events,now);return upcoming.find(event=>!event.allDay)??upcoming[0]}
